include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"

linter:
  rules:
    prefer_function_declarations_over_variables: false
    sort_pub_dependencies: false
    prefer_single_quotes: true
    overridden_fields: false
    avoid_classes_with_only_static_members: false
    prefer_relative_imports: true
    constant_identifier_names: false
    noop_primitive_operations: false
    avoid_multiple_declarations_per_line: false
    depend_on_referenced_packages: false
    use_build_context_synchronously: false
    await_only_futures: false
    invalid_annotation_target: false
    cast_nullable_to_non_nullable: false
