// ignore_for_file: prefer_single_quotes
final List<Map<String, dynamic>> country = [
    {"name": "Malaysia", "dial_code": "+60", "locale": "MY"},
  {"name": "Afghanistan", "dial_code": "+93", "locale": "AF"},
  {"name": "Aland Islands", "dial_code": "+358", "locale": "AX"},
  {"name": "Albania", "dial_code": "+355", "locale": "AL"},
  {"name": "Algeria", "dial_code": "+213", "locale": "DZ"},
  {"name": "AmericanSamoa", "dial_code": "+1684", "locale": "AS"},
  {"name": "Andorra", "dial_code": "+376", "locale": "AD"},
  {"name": "Angola", "dial_code": "+244", "locale": "AO"},
  {"name": "Anguilla", "dial_code": "+1264", "locale": "AI"},
  {"name": "Antarctica", "dial_code": "+672", "locale": "AQ"},
  {"name": "Antigua and Barbuda", "dial_code": "+1268", "locale": "AG"},
  {"name": "Argentina", "dial_code": "+54", "locale": "AR"},
  {"name": "Armenia", "dial_code": "+374", "locale": "AM"},
  {"name": "Aruba", "dial_code": "+297", "locale": "AW"},
  {"name": "Australia", "dial_code": "+61", "locale": "AU"},
  {"name": "Austria", "dial_code": "+43", "locale": "AT"},
  {"name": "Azerbaijan", "dial_code": "+994", "locale": "AZ"},
  {"name": "Bahamas", "dial_code": "+1242", "locale": "BS"},
  {"name": "Bahrain", "dial_code": "+973", "locale": "BH"},
  {"name": "Bangladesh", "dial_code": "+880", "locale": "BD"},
  {"name": "Barbados", "dial_code": "+1246", "locale": "BB"},
  {"name": "Belarus", "dial_code": "+375", "locale": "BY"},
  {"name": "Belgium", "dial_code": "+32", "locale": "BE"},
  {"name": "Belize", "dial_code": "+501", "locale": "BZ"},
  {"name": "Benin", "dial_code": "+229", "locale": "BJ"},
  {"name": "Bermuda", "dial_code": "+1441", "locale": "BM"},
  {"name": "Bhutan", "dial_code": "+975", "locale": "BT"},
  {
    "name": "Bolivia, Plurinational State of",
    "dial_code": "+591",
    "locale": "BO"
  },
  {"name": "Bosnia and Herzegovina", "dial_code": "+387", "locale": "BA"},
  {"name": "Botswana", "dial_code": "+267", "locale": "BW"},
  {"name": "Brazil", "dial_code": "+55", "locale": "BR"},
  {
    "name": "British Indian Ocean Territory",
    "dial_code": "+246",
    "locale": "IO"
  },
  {"name": "Brunei Darussalam", "dial_code": "+673", "locale": "BN"},
  {"name": "Bulgaria", "dial_code": "+359", "locale": "BG"},
  {"name": "Burkina Faso", "dial_code": "+226", "locale": "BF"},
  {"name": "Burundi", "dial_code": "+257", "locale": "BI"},
  {"name": "Cambodia", "dial_code": "+855", "locale": "KH"},
  {"name": "Cameroon", "dial_code": "+237", "locale": "CM"},
  {"name": "Canada", "dial_code": "+1", "locale": "CA"},
  {"name": "Cape Verde", "dial_code": "+238", "locale": "CV"},
  {"name": "Cayman Islands", "dial_code": "+1-345", "locale": "KY"},
  {"name": "Central African Republic", "dial_code": "+236", "locale": "CF"},
  {"name": "Chad", "dial_code": "+235", "locale": "TD"},
  {"name": "Chile", "dial_code": "+56", "locale": "CL"},
  {"name": "China", "dial_code": "+86", "locale": "CN"},
  {"name": "Christmas Island", "dial_code": "+61", "locale": "CX"},
  {"name": "Cocos (Keeling) Islands", "dial_code": "+61", "locale": "CC"},
  {"name": "Colombia", "dial_code": "+57", "locale": "CO"},
  {"name": "Comoros", "dial_code": "+269", "locale": "KM"},
  {"name": "Congo", "dial_code": "+242", "locale": "CG"},
  {
    "name": "Congo, The Democratic Republic of the Congo",
    "dial_code": "+243",
    "locale": "CD"
  },
  {"name": "Cook Islands", "dial_code": "+682", "locale": "CK"},
  {"name": "Costa Rica", "dial_code": "+506", "locale": "CR"},
  {"name": "Cote d'Ivoire", "dial_code": "+225", "locale": "CI"},
  {"name": "Croatia", "dial_code": "+385", "locale": "HR"},
  {"name": "Cuba", "dial_code": "+53", "locale": "CU"},
  {"name": "Cyprus", "dial_code": "+357", "locale": "CY"},
  {"name": "Czech Republic", "dial_code": "+420", "locale": "CZ"},
  {"name": "Denmark", "dial_code": "+45", "locale": "DK"},
  {"name": "Djibouti", "dial_code": "+253", "locale": "DJ"},
  {"name": "Dominica", "dial_code": "+1767", "locale": "DM"},
  {"name": "Dominican Republic", "dial_code": "+1849", "locale": "DO"},
  {"name": "Ecuador", "dial_code": "+593", "locale": "EC"},
  {"name": "Egypt", "dial_code": "+20", "locale": "EG"},
  {"name": "El Salvador", "dial_code": "+503", "locale": "SV"},
  {"name": "Equatorial Guinea", "dial_code": "+240", "locale": "GQ"},
  {"name": "Eritrea", "dial_code": "+291", "locale": "ER"},
  {"name": "Estonia", "dial_code": "+372", "locale": "EE"},
  {"name": "Ethiopia", "dial_code": "+251", "locale": "ET"},
  {"name": "Falkland Islands (Malvinas)", "dial_code": "+500", "locale": "FK"},
  {"name": "Faroe Islands", "dial_code": "+298", "locale": "FO"},
  {"name": "Fiji", "dial_code": "+679", "locale": "FJ"},
  {"name": "Finland", "dial_code": "+358", "locale": "FI"},
  {"name": "France", "dial_code": "+33", "locale": "FR"},
  {"name": "French Guiana", "dial_code": "+594", "locale": "GF"},
  {"name": "French Polynesia", "dial_code": "+689", "locale": "PF"},
  {"name": "Gabon", "dial_code": "+241", "locale": "GA"},
  {"name": "Gambia", "dial_code": "+220", "locale": "GM"},
  {"name": "Georgia", "dial_code": "+995", "locale": "GE"},
  {"name": "Germany", "dial_code": "+49", "locale": "DE"},
  {"name": "Ghana", "dial_code": "+233", "locale": "GH"},
  {"name": "Gibraltar", "dial_code": "+350", "locale": "GI"},
  {"name": "Greece", "dial_code": "+30", "locale": "GR"},
  {"name": "Greenland", "dial_code": "+299", "locale": "GL"},
  {"name": "Grenada", "dial_code": "+1473", "locale": "GD"},
  {"name": "Guadeloupe", "dial_code": "+590", "locale": "GP"},
  {"name": "Guam", "dial_code": "+1671", "locale": "GU"},
  {"name": "Guatemala", "dial_code": "+502", "locale": "GT"},
  {"name": "Guernsey", "dial_code": "+44", "locale": "GG"},
  {"name": "Guinea", "dial_code": "+224", "locale": "GN"},
  {"name": "Guinea-Bissau", "dial_code": "+245", "locale": "GW"},
  {"name": "Guyana", "dial_code": "+595", "locale": "GY"},
  {"name": "Haiti", "dial_code": "+509", "locale": "HT"},
  {
    "name": "Holy See (Vatican City State)",
    "dial_code": "+379",
    "locale": "VA"
  },
  {"name": "Honduras", "dial_code": "+504", "locale": "HN"},
  {"name": "Hong Kong", "dial_code": "+852", "locale": "HK"},
  {"name": "Hungary", "dial_code": "+36", "locale": "HU"},
  {"name": "Iceland", "dial_code": "+354", "locale": "IS"},
  {"name": "India", "dial_code": "+91", "locale": "IN"},
  {"name": "Indonesia", "dial_code": "+62", "locale": "ID"},
  {
    "name": "Iran, Islamic Republic of Persian Gulf",
    "dial_code": "+98",
    "locale": "IR"
  },
  {"name": "Iraq", "dial_code": "+964", "locale": "IQ"},
  {"name": "Ireland", "dial_code": "+353", "locale": "IE"},
  {"name": "Isle of Man", "dial_code": "+44", "locale": "IM"},
  {"name": "Israel", "dial_code": "+972", "locale": "IL"},
  {"name": "Italy", "dial_code": "+39", "locale": "IT"},
  {"name": "Jamaica", "dial_code": "+1876", "locale": "JM"},
  {"name": "Japan", "dial_code": "+81", "locale": "JP"},
  {"name": "Jersey", "dial_code": "+44", "locale": "JE"},
  {"name": "Jordan", "dial_code": "+962", "locale": "JO"},
  {"name": "Kazakhstan", "dial_code": "+77", "locale": "KZ"},
  {"name": "Kenya", "dial_code": "+254", "locale": "KE"},
  {"name": "Kiribati", "dial_code": "+686", "locale": "KI"},
  {
    "name": "Korea, Democratic People's Republic of Korea",
    "dial_code": "+850",
    "locale": "KP"
  },
  {
    "name": "Korea, Republic of South Korea",
    "dial_code": "+82",
    "locale": "KR"
  },
  {"name": "Kuwait", "dial_code": "+965", "locale": "KW"},
  {"name": "Kyrgyzstan", "dial_code": "+996", "locale": "KG"},
  {"name": "Laos", "dial_code": "+856", "locale": "LA"},
  {"name": "Latvia", "dial_code": "+371", "locale": "LV"},
  {"name": "Lebanon", "dial_code": "+961", "locale": "LB"},
  {"name": "Lesotho", "dial_code": "+266", "locale": "LS"},
  {"name": "Liberia", "dial_code": "+231", "locale": "LR"},
  {"name": "Libyan Arab Jamahiriya", "dial_code": "+218", "locale": "LY"},
  {"name": "Liechtenstein", "dial_code": "+423", "locale": "LI"},
  {"name": "Lithuania", "dial_code": "+370", "locale": "LT"},
  {"name": "Luxembourg", "dial_code": "+352", "locale": "LU"},
  {"name": "Macao", "dial_code": "+853", "locale": "MO"},
  {"name": "Macedonia", "dial_code": "+389", "locale": "MK"},
  {"name": "Madagascar", "dial_code": "+261", "locale": "MG"},
  {"name": "Malawi", "dial_code": "+265", "locale": "MW"},
  {"name": "Malaysia", "dial_code": "+60", "locale": "MY"},
  {"name": "Maldives", "dial_code": "+960", "locale": "MV"},
  {"name": "Mali", "dial_code": "+223", "locale": "ML"},
  {"name": "Malta", "dial_code": "+356", "locale": "MT"},
  {"name": "Marshall Islands", "dial_code": "+692", "locale": "MH"},
  {"name": "Martinique", "dial_code": "+596", "locale": "MQ"},
  {"name": "Mauritania", "dial_code": "+222", "locale": "MR"},
  {"name": "Mauritius", "dial_code": "+230", "locale": "MU"},
  {"name": "Mayotte", "dial_code": "+262", "locale": "YT"},
  {"name": "Mexico", "dial_code": "+52", "locale": "MX"},
  {
    "name": "Micronesia, Federated States of Micronesia",
    "dial_code": "+691",
    "locale": "FM"
  },
  {"name": "Moldova", "dial_code": "+373", "locale": "MD"},
  {"name": "Monaco", "dial_code": "+377", "locale": "MC"},
  {"name": "Mongolia", "dial_code": "+976", "locale": "MN"},
  {"name": "Montenegro", "dial_code": "+382", "locale": "ME"},
  {"name": "Montserrat", "dial_code": "+1664", "locale": "MS"},
  {"name": "Morocco", "dial_code": "+212", "locale": "MA"},
  {"name": "Mozambique", "dial_code": "+258", "locale": "MZ"},
  {"name": "Myanmar", "dial_code": "+95", "locale": "MM"},
  {"name": "Namibia", "dial_code": "+264", "locale": "NA"},
  {"name": "Nauru", "dial_code": "+674", "locale": "NR"},
  {"name": "Nepal", "dial_code": "+977", "locale": "NP"},
  {"name": "Netherlands", "dial_code": "+31", "locale": "NL"},
  {"name": "Netherlands Antilles", "dial_code": "+599", "locale": "AN"},
  {"name": "New Caledonia", "dial_code": "+687", "locale": "NC"},
  {"name": "New Zealand", "dial_code": "+64", "locale": "NZ"},
  {"name": "Nicaragua", "dial_code": "+505", "locale": "NI"},
  {"name": "Niger", "dial_code": "+227", "locale": "NE"},
  {"name": "Nigeria", "dial_code": "+234", "locale": "NG"},
  {"name": "Niue", "dial_code": "+683", "locale": "NU"},
  {"name": "Norfolk Island", "dial_code": "+672", "locale": "NF"},
  {"name": "Northern Mariana Islands", "dial_code": "+1670", "locale": "MP"},
  {"name": "Norway", "dial_code": "+47", "locale": "NO"},
  {"name": "Oman", "dial_code": "+968", "locale": "OM"},
  {"name": "Pakistan", "dial_code": "+92", "locale": "PK"},
  {"name": "Palau", "dial_code": "+680", "locale": "PW"},
  {
    "name": "Palestinian Territory, Occupied",
    "dial_code": "+970",
    "locale": "PS"
  },
  {"name": "Panama", "dial_code": "+507", "locale": "PA"},
  {"name": "Papua New Guinea", "dial_code": "+675", "locale": "PG"},
  {"name": "Paraguay", "dial_code": "+595", "locale": "PY"},
  {"name": "Peru", "dial_code": "+51", "locale": "PE"},
  {"name": "Philippines", "dial_code": "+63", "locale": "PH"},
  {"name": "Pitcairn", "dial_code": "+872", "locale": "PN"},
  {"name": "Poland", "dial_code": "+48", "locale": "PL"},
  {"name": "Portugal", "dial_code": "+351", "locale": "PT"},
  {"name": "Puerto Rico", "dial_code": "+1939", "locale": "PR"},
  {"name": "Qatar", "dial_code": "+974", "locale": "QA"},
  {"name": "Romania", "dial_code": "+40", "locale": "RO"},
  {"name": "Russia", "dial_code": "+7", "locale": "RU"},
  {"name": "Rwanda", "dial_code": "+250", "locale": "RW"},
  {"name": "Reunion", "dial_code": "+262", "locale": "RE"},
  {"name": "Saint Barthelemy", "dial_code": "+590", "locale": "BL"},
  {
    "name": "Saint Helena, Ascension and Tristan Da Cunha",
    "dial_code": "+290",
    "locale": "SH"
  },
  {"name": "Saint Kitts and Nevis", "dial_code": "+1869", "locale": "KN"},
  {"name": "Saint Lucia", "dial_code": "+1758", "locale": "LC"},
  {"name": "Saint Martin", "dial_code": "+590", "locale": "MF"},
  {"name": "Saint Pierre and Miquelon", "dial_code": "+508", "locale": "PM"},
  {
    "name": "Saint Vincent and the Grenadines",
    "dial_code": "+1784",
    "locale": "VC"
  },
  {"name": "Samoa", "dial_code": "+685", "locale": "WS"},
  {"name": "San Marino", "dial_code": "+378", "locale": "SM"},
  {"name": "Sao Tome and Principe", "dial_code": "+239", "locale": "ST"},
  {"name": "Saudi Arabia", "dial_code": "+966", "locale": "SA"},
  {"name": "Senegal", "dial_code": "+221", "locale": "SN"},
  {"name": "Serbia", "dial_code": "+381", "locale": "RS"},
  {"name": "Seychelles", "dial_code": "+248", "locale": "SC"},
  {"name": "Sierra Leone", "dial_code": "+232", "locale": "SL"},
  {"name": "Singapore", "dial_code": "+65", "locale": "SG"},
  {"name": "Slovakia", "dial_code": "+421", "locale": "SK"},
  {"name": "Slovenia", "dial_code": "+386", "locale": "SI"},
  {"name": "Solomon Islands", "dial_code": "+677", "locale": "SB"},
  {"name": "Somalia", "dial_code": "+252", "locale": "SO"},
  {"name": "South Africa", "dial_code": "+27", "locale": "ZA"},
  {"name": "South Sudan", "dial_code": "+211", "locale": "SS"},
  {
    "name": "South Georgia and the South Sandwich Islands",
    "dial_code": "+500",
    "locale": "GS"
  },
  {"name": "Spain", "dial_code": "+34", "locale": "ES"},
  {"name": "Sri Lanka", "dial_code": "+94", "locale": "LK"},
  {"name": "Sudan", "dial_code": "+249", "locale": "SD"},
  {"name": "Suriname", "dial_code": "+597", "locale": "SR"},
  {"name": "Svalbard and Jan Mayen", "dial_code": "+47", "locale": "SJ"},
  {"name": "Swaziland", "dial_code": "+268", "locale": "SZ"},
  {"name": "Sweden", "dial_code": "+46", "locale": "SE"},
  {"name": "Switzerland", "dial_code": "+41", "locale": "CH"},
  {"name": "Syrian Arab Republic", "dial_code": "+963", "locale": "SY"},
  {"name": "Taiwan", "dial_code": "+886", "locale": "TW"},
  {"name": "Tajikistan", "dial_code": "+992", "locale": "TJ"},
  {
    "name": "Tanzania, United Republic of Tanzania",
    "dial_code": "+255",
    "locale": "TZ"
  },
  {"name": "Thailand", "dial_code": "+66", "locale": "TH"},
  {"name": "Timor-Leste", "dial_code": "+670", "locale": "TL"},
  {"name": "Togo", "dial_code": "+228", "locale": "TG"},
  {"name": "Tokelau", "dial_code": "+690", "locale": "TK"},
  {"name": "Tonga", "dial_code": "+676", "locale": "TO"},
  {"name": "Trinidad and Tobago", "dial_code": "+1868", "locale": "TT"},
  {"name": "Tunisia", "dial_code": "+216", "locale": "TN"},
  {"name": "Turkey", "dial_code": "+90", "locale": "TR"},
  {"name": "Turkmenistan", "dial_code": "+993", "locale": "TM"},
  {"name": "Turks and Caicos Islands", "dial_code": "+1649", "locale": "TC"},
  {"name": "Tuvalu", "dial_code": "+688", "locale": "TV"},
  {"name": "Uganda", "dial_code": "+256", "locale": "UG"},
  {"name": "Ukraine", "dial_code": "+380", "locale": "UA"},
  {"name": "United Arab Emirates", "dial_code": "+971", "locale": "AE"},
  {"name": "United Kingdom", "dial_code": "+44", "locale": "GB"},
  {"name": "United States", "dial_code": "+1", "locale": "US"},
  {"name": "Uruguay", "dial_code": "+598", "locale": "UY"},
  {"name": "Uzbekistan", "dial_code": "+998", "locale": "UZ"},
  {"name": "Vanuatu", "dial_code": "+678", "locale": "VU"},
  {
    "name": "Venezuela, Bolivarian Republic of Venezuela",
    "dial_code": "+58",
    "locale": "VE"
  },
  {"name": "Vietnam", "dial_code": "+84", "locale": "VN"},
  {"name": "Virgin Islands, British", "dial_code": "+1284", "locale": "VG"},
  {"name": "Virgin Islands, U.S.", "dial_code": "+1340", "locale": "VI"},
  {"name": "Wallis and Futuna", "dial_code": "+681", "locale": "WF"},
  {"name": "Yemen", "dial_code": "+967", "locale": "YE"},
  {"name": "Zambia", "dial_code": "+260", "locale": "ZM"},
  {"name": "Zimbabwe", "dial_code": "+263", "locale": "ZW"}
];
